language: go

go:
    - "1.11"
    - "1.12"
    - tip

env:
  - GOLANGCILINT=$(curl -fsSLI -o /dev/null -w %{url_effective} https://github.com/golangci/golangci-lint/releases/latest | awk -F '/' '{print $8}')

go_import_path: github.com/intel/ccloudvm

matrix:
  allow_failures:
  - go: tip

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCILINT}

script:
   - go env
   - golangci-lint run -c ./.golangci.yml ./...
